---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./
    enforce_order: False
  dnsimple:
    class: octodns.provider.dnsimple.DnsimpleProvider
    token: env/DNSIMPLE_API_KEY
    account: env/DNSIMPLE_ACCOUNT_NUMBER
    delete_pcent_threshold: 1.0

zones:
  "*":
    sources:
      - config
    targets:
      - dnsimple
